### ISSUE TITLE
make_shard_list.py problem for gigaspeech 

### ISSUE THREAD

**Issue by agreatbush** [wenet-e2e/wenet#1161]
when i using make_shard_list.py to make shard for gigaspeech ,there is no wrong output but always some *.tar file generated by it can not readable.

**Comment by robin1001** [comment]
We didn't do verfication carefully of `shard` on gigaspeech, please try to debug the problem, and looking forward to your fix.

**Comment by duj12** [comment]
> when i using make_shard_list.py to make shard for gigaspeech ,there is no wrong output but always some *.tar file generated by it can not readable.

@agreatbush I meet the same problem. After I read the 'tools/make_shard_list.py', I may have found the reason. There must be something wrong when generating the TAR file. But when someting wrong, the log may miss the information. 

In my case, I have some audio with ".WAV" suffix, so this line will throw a ASSERTION ERROR    [         assert suffix in AUDIO_FORMAT_SETS](https://github.com/wenet-e2e/wenet/blob/999f6ef4f21987324776f5c8be86c2b18377b66f/tools/make_shard_list.py#L51).
But the ERROR message is Missed in the log, I think maybe it's because the multiprocessing.

These ERRORs may cause each processing ABORT, so the TAR file is not completed. 
'tools/make_shard_list.py' now is not perfect to handle all cases of the input, check your wav and text first.

**Comment by yxf0605** [comment]
I encountered similar problems. After debuging, I found that the script will hang when it transcode large opus file(maybe OOM happens). My solution is  transcode large opus file into wav files offline, then change the scripts to read wav files.
