### ISSUE TITLE
I'm a newer ,i use wenet_wenetspeech model but  it seems lack a file names  units.txt.

### ISSUE THREAD

**Issue by lili161** [wenet-e2e/wenet#1450]
I'm a newer ,i use wenet_wenetspeech model but  it seems lack a file names  units.txt.
this is my code 
![image](https://user-images.githubusercontent.com/44579502/190540878-d2af84f0-c838-47a8-8d76-5da99b284cc1.png)
and this is model dir 
![image](https://user-images.githubusercontent.com/44579502/190540980-299b9b9a-3b1c-4ba4-8c59-93b9de9accb2.png)

I wanna know if i do the wrong step,and how can i fix it ,thank you.

**Comment by dophist** [comment]
@robin1001 Since this is related to [SpeechColab/Leaderboard project](https://github.com/SpeechColab/Leaderboard), so this is kind of my concern as well.

When intial released, the WeNet pretrained model was submitted to leaderboard project, many have downloaded it and try it via the leaderboard.  But later no one seems to be maintaining the model, hence being broken and not to be reproducible any more.

Actually, if properly done, the submitted model can be maintenance-free and be always reproducible by others:
* by specifying the specific OS version in Dockerfile, such as Ubuntu 18.04, instead of just Ubuntu latest
* by specifying the concrete WeNet repo's commit ID that is compatible with submitted model, so the model won't break as your community evolves
* by removing dependent links that might be invalid in future (Last time I try I found some hosting links from Mobvoi are no longer available)

With these adaptation, the models in Leaderboard can be usable and reproducible, by anyone, say, even 10 years later.  I would suggest so if your community has someone can do this, not much work, really. It would be better if you guys can update the pretrained model to the latest release with best accuracy. 

Otherwise, there will always be someone not knowing this broken state, and asking related questions, either in WeNet, or in Leaderboard.

**Comment by dophist** [comment]
By the way, submit an English pretrained model as well if you can.  Leaderboard is going to release English benchmark as well, a performing pretrained model can help you community grow.  And with the success of Chinese model submission, the effort for adding an extra English model should be trivial.

**Comment by lili161** [comment]
You right,it's version problem,thank you.
