### ISSUE TITLE
the mismatch between result_.sentence and result_.word_pieces when using TLG decoding？

### ISSUE THREAD

**Issue by zyjcsf** [wenet-e2e/wenet#1531]
Hello,
when I use TLG decode ,I find the result_[0].sentence and result_[0].word_pieces are difference, the result_[0].sentence is generated by searcher_->Outputs()（the TLG outputs_[0]）,and  the result_[0].word_pieces are based on searcher_->Inputs()（the  TLG  alignment）. There is a difference between the two results especially when the recognition result contains repeated words.This also causes the results of the timestamp to be inconsistent with the final recognition result. 
Is there any way to keep them consistent?

Thank you very much.

**Comment by robin1001** [comment]
Yes, for TLG(with LM) decoding, result[0].sentence is gererated by `searcher->Outputs()` since it is the output unit of TLG. However, timestamp is generated by our modeling units(searcher->Inputs()), which is designed in the way on purpose since we can get more accurate timestamp with smaller units.

**Comment by xingchensong** [comment]
Thanks for pointing it out, this is a normal behaviour as explaned by robin1001. 

I will hold this PR for anyone else who has encountered and interested in the same question.
