### ISSUE TITLE
How to calculate WER of onnx model ?

### ISSUE THREAD

**Issue by neso613** [wenet-e2e/wenet#1536]
Hey 
I have taken pretarined AIShell model from [WENET repo](https://wenet.org.cn/wenet/pretrained_models.html) and converted that into ONNX using [this code](https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_onnx_cpu.py).

Now I want to check the WER of converted model using [this code ](https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize_onnx.py) but got error and the reason of this is following -

`parser.add_argument('--config', required=True, help='config file')
    parser.add_argument('--test_data', required=True, help='test data file')
    parser.add_argument('--dict', required=True, help='dict file')`

- config file is train_yaml file which is downloaded with the checkpoints
- test_data is, I suppose, the folder having test wavs
- dict is data.list (as given in this [link](https://wenet.org.cn/wenet/tutorial_aishell.html#stage-3-prepare-wenet-data-format))

error that I get is as follows-
`Traceback (most recent call last):
  File "/home/c/anaconda3/envs/wenet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/c/anaconda3/envs/wenet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/c/wenet/wenet/bin/recognize.py", line 311, in <module>
    main()
  File "/home/c/wenet/wenet/bin/recognize.py", line 153, in main
    symbol_table = read_symbol_table(args.dict)
  File "/home/c/wenet/wenet/utils/file_utils.py", line 65, in read_symbol_table
    assert len(arr) == 2
AssertionError
`

Please let me know what and where I am missing or doing wrong.

**Comment by neso613** [comment]
@xingchensong

**Comment by xingchensong** [comment]
1. testdata is data.list
2. dict is character dictionary ,located in download *.tar

**Comment by neso613** [comment]
@xingchensong  
I have chnaged the testdata and dict as per your suggestion and it eliminates the error but it does not server the result.

The data.list have this structure -
![image](https://user-images.githubusercontent.com/31642462/199918515-794e2c9c-9255-4f9e-be2f-2267a7aea911.png)
 and after the run, I got this... `2022-11-04 13:04:32,170 WARNING Failed to open`

and no output generated.

**Comment by neso613** [comment]
Hi @xingchensong 
I have solved the above asked problem.. that issue was 'raw' and 'shard' type.

But now,please help me to get the answer of this error-
After model conversion to onnx using[ this code](https://github.com/wenet-e2e/wenet/tree/main/runtime/onnxruntime), model is converted with these logs -

`onnx_encoder inputs : ['chunk', 'offset', 'att_cache', 'cnn_cache']
		onnx_encoder input shapes : [[1, 0, 80], [], [12, 4, 0, 128], [12, 1, 256, 7]]
		onnx_encoder outputs: ['output', 'r_att_cache', 'r_cnn_cache']
		onnx_encoder output shapes : [[0, 0, 256], [12, 4, 0, 128], [12, 1, 256, 0]]


onnx_decoder inputs : ['hyps', 'hyps_lens', 'encoder_out']
		onnx_decoder input shapes : [[0, 0], [0], [1, 0, 256]]

 torch.onnx.export
		onnx_ctc inputs : ['hidden']
		onnx_ctc input shapes : [[1, 0, 256]]
		onnx_ctc outputs: ['probs']
		onnx_ctc output shapes : [[1, 0, 4233]]
`

Now, if I run the [decoding code ](https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize_onnx.py)
I got this error -
`File "/home/c/wenet/wenet/bin/recognize_onnx.py", line 177, in main
    ort_outs = encoder_ort_session.run(None, ort_inputs)
  File "/home/c/anaconda3/envs/wenet/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 196, in run
    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
ValueError: Model requires 4 inputs. Input Feed contains 2
`

Please help in this regard.

**Comment by xingchensong** [comment]
As I have said，if your model is exported using export_onnx_cpu.py，you !must! use cpp runtime. python script only support export_onnx_gpu.py发自我的 iPhone在 2022年11月6日，20:24，neso613 ***@***.***> 写道：﻿
Hi @xingchensong
I have solved the above asked problem.. that issue was 'raw' and 'shard' type.
But now,please help me to get the answer of this error-
After model conversion to onnx using this code, model is converted with these logs -
`onnx_encoder inputs : ['chunk', 'offset', 'att_cache', 'cnn_cache']
onnx_encoder input shapes : [[1, 0, 80], [], [12, 4, 0, 128], [12, 1, 256, 7]]
onnx_encoder outputs: ['output', 'r_att_cache', 'r_cnn_cache']
onnx_encoder output shapes : [[0, 0, 256], [12, 4, 0, 128], [12, 1, 256, 0]]
onnx_decoder inputs : ['hyps', 'hyps_lens', 'encoder_out']
onnx_decoder input shapes : [[0, 0], [0], [1, 0, 256]]
torch.onnx.export
onnx_ctc inputs : ['hidden']
onnx_ctc input shapes : [[1, 0, 256]]
onnx_ctc outputs: ['probs']
onnx_ctc output shapes : [[1, 0, 4233]]
`
Now, if I run the decoding code 
I got this error -
File "/home/c/wenet/wenet/bin/recognize_onnx.py", line 177, in main ort_outs = encoder_ort_session.run(None, ort_inputs) File "/home/c/anaconda3/envs/wenet/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 196, in run raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs)) ValueError: Model requires 4 inputs. Input Feed contains 2 
Please help in this regard.

**Comment by neso613** [comment]
Thank @xingchensong for eplying.

I had tried that too but failed to complile that...pls see [this](https://github.com/wenet-e2e/wenet/issues/1458#issuecomment-1301914447) and suggest.

**Comment by neso613** [comment]
Hi @xingchensong  Thanks for updating the repo.
I followed your suggestion and run the same scipt on GPU after exporting onnx model using its equivalent export_onnx_gpu script.

I got this error and requires your thoughts on it.. 
`Namespace(batch_size=32, bpe_model=None, config='pretrained_model/20210601_u2++_conformer_libtorch/20210601_u2++_conformer_exp/train.yaml', data_type='raw', decoder_onnx='onnx_gpu/decoder.onnx', dict='pretrained_model/20210601_u2++_conformer_libtorch/20210601_u2++_conformer_exp/units.txt', encoder_onnx='onnx_gpu/encoder.onnx', fp16=False, gpu=-1, mode='attention_rescoring', override_config=[], result_file='result_file_onnx.txt', test_data='examples/aishell/s0/data/dev/data.list')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/wenet/wenet/bin/recognize_onnx_gpu.py", line 278, in <module>
    main()
  File "/workspace/wenet/wenet/bin/recognize_onnx_gpu.py", line 228, in main
    hyps += (beam_size - cur_len) * [(-float("INF"), (0,))]
TypeError: can only concatenate tuple (not "list") to tuple
`

thanks
