### ISSUE TITLE
How to add new words during fine-tuning？

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#2467]
Hi，a pre-trained model's unit.txt contains 1000 words. When fine-tuning based on this pre-trained model, there are 10 new words not in the unit.txt. At this point, adding these 10 new words to the end of unit.txt and assigning them new numbers, is this approach feasible?

**Comment by fclearner** [comment]
freeze other modules except the outputlayer(ctc output && attention decoder output), add new words to your unit.txt ,modify the output size and then tune the model

**Comment by srdfjy** [comment]
THX @fclearner，I will try out what you suggested later.

**Comment by LiSongRan** [comment]
@fclearner  embedd layer in the decoder doesn't need to be changed??

**Comment by fclearner** [comment]
> @fclearner embedd layer in the decoder doesn't need to be changed??

Found modules match the output size and change it

**Comment by fclearner** [comment]
>  provide examples ?
> 
> 
> 

Try to print the model size or visualize it with netron

**Comment by LiSongRan** [comment]
the issue here?

2024-07-12 18:36:40,613 INFO missing tensor: encoder.embed.pos_enc.pe
2024-07-12 18:36:40,613 INFO missing tensor: decoder.left_decoder.embed.1.pe
2024-07-12 18:36:40,613 INFO missing tensor: decoder.right_decoder.embed.1.pe
{'encoder': 'conformer', 'encoder_conf': {'activation_type': 'swish', 'attention_dropout_rate': 0.1, 'attention_heads': 8, 'causal': True, 'cnn_module_kernel': 15, 'cnn_module_norm': 'laye                                                r_norm', 'dropout_rate': 0.1, 'input_layer': 'conv2d', 'linear_units': 2048, 'normalize_before': True, 'num_blocks': 12, 'output_size': 512, 'pos_enc_layer_type': 'rel_pos', 'positional_dr                                                opout_rate': 0.1, 'selfattention_layer_type': 'rel_selfattn', 'use_cnn_module': True, 'use_dynamic_chunk': True, 'use_dynamic_left_chunk': False}, 'decoder': 'bitransformer', 'decoder_conf                                                ': {'attention_heads': 8, 'dropout_rate': 0.1, 'linear_units': 2048, 'num_blocks': 3, 'positional_dropout_rate': 0.1, 'r_num_blocks': 3, 'self_attention_dropout_rate': 0.1, 'src_attention_                                                dropout_rate': 0.1}, 'tokenizer': 'char', 'tokenizer_conf': {'symbol_table_path': '/home/SpeechRecognitioin/wenet/data/20220506_u2pp_conformer_exp_wenetspeech//units.txt', 'split_with_spac                                                e': False, 'bpe_path': None, 'non_lang_syms_path': None, 'is_multilingual': False, 'num_languages': 1, 'special_tokens': {'<blank>': 0, '<unk>': 1, '<sos>': 2, '<eos>': 2}}, 'ctc': 'ctc',                                                 'ctc_conf': {'ctc_blank_id': 0}, 'cmvn': 'global_cmvn', 'cmvn_conf': {'cmvn_file': '/home/SpeechRecognitioin/wenet/data/20220506_u2pp_conformer_exp_wenetspeech//global_cmvn', 'is_json_cmvn                                                ': True}, 'model': 'asr_model', 'model_conf': {'ctc_weight': 0.3, 'lsm_weight': 0.1, 'length_normalized_loss': False, 'reverse_weight': 0.3}, 'dataset': 'asr', 'dataset_conf': {'batch_conf                                                ': {'batch_size': 96, 'batch_type': 'dynamic', 'max_frames_in_batch': 24000}, 'fbank_conf': {'dither': 1.0, 'frame_length': 25, 'frame_shift': 10, 'num_mel_bins': 80}, 'filter_conf': {'max                                                _length': 1200, 'min_length': 10, 'token_max_length': 100, 'token_min_length': 1}, 'resample_conf': {'resample_rate': 16000}, 'shuffle': True, 'shuffle_conf': {'shuffle_size': 20000}, 'sor                                                t': True, 'sort_conf': {'sort_size': 2000}, 'spec_aug': True, 'spec_aug_conf': {'max_f': 30, 'max_t': 50, 'num_f_mask': 2, 'num_t_mask': 2}, 'speed_perturb': True}, 'input_dim': 80, 'outpu                                                t_dim': 5564, 'grad_clip': 5, 'accum_grad': 16, 'max_epoch': 400, 'log_interval': 500, 'optim': 'adam', 'optim_conf': {'lr': 0.002}, 'scheduler': 'warmuplr', 'scheduler_conf': {'warmup_ste                                                ps': 100000}, 'vocab_size': 5564, 'dtype': 'fp32', 'train_engine': 'torch_ddp', 'use_amp': False, 'model_dir': 'exp/conformer', 'save_states': 'model_only', 'init_infos': {}}
2024-07-12 18:36:41,257 INFO [Rank 0] Checkpoint: save to checkpoint exp/conformer/init.pt
DistributedDataParallel(
  (module): ASRModel(
    (encoder): ConformerEncoder(
      (global_cmvn): GlobalCMVN()
      (embed): Conv2dSubsampling4(
        (conv): Sequential(
          (0): Conv2d(1, 512, kernel_size=(3, 3), stride=(2, 2))
          (1): ReLU()
          (2): Conv2d(512, 512, kernel_size=(3, 3), stride=(2, 2))
          (3): ReLU()
        )
        (out): Sequential(
          (0): Linear(in_features=9728, out_features=512, bias=True)
        )
        (pos_enc): RelPositionalEncoding(
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (after_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (encoders): ModuleList(
        (0-11): 12 x ConformerEncoderLayer(
          (self_attn): RelPositionMultiHeadedAttention(
            (linear_q): Linear(in_features=512, out_features=512, bias=True)
            (linear_k): Linear(in_features=512, out_features=512, bias=True)
            (linear_v): Linear(in_features=512, out_features=512, bias=True)
            (linear_out): Linear(in_features=512, out_features=512, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
            (linear_pos): Linear(in_features=512, out_features=512, bias=False)
          )
          (feed_forward): PositionwiseFeedForward(
            (w_1): Linear(in_features=512, out_features=2048, bias=True)
            (activation): SiLU()
            (dropout): Dropout(p=0.1, inplace=False)
            (w_2): Linear(in_features=2048, out_features=512, bias=True)
          )
          (feed_forward_macaron): PositionwiseFeedForward(
            (w_1): Linear(in_features=512, out_features=2048, bias=True)
            (activation): SiLU()
            (dropout): Dropout(p=0.1, inplace=False)
            (w_2): Linear(in_features=2048, out_features=512, bias=True)
          )
          (conv_module): ConvolutionModule(
            (pointwise_conv1): Conv1d(512, 1024, kernel_size=(1,), stride=(1,))
            (depthwise_conv): Conv1d(512, 512, kernel_size=(15,), stride=(1,), groups=512)
            (norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
            (pointwise_conv2): Conv1d(512, 512, kernel_size=(1,), stride=(1,))
            (activation): SiLU()
          )
          (norm_ff): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
          (norm_mha): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
          (norm_ff_macaron): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
          (norm_conv): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
          (norm_final): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (decoder): BiTransformerDecoder(
      (left_decoder): TransformerDecoder(
        (embed): Sequential(
          (0): Embedding(5564, 512)
          (1): PositionalEncoding(
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (after_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (output_layer): Linear(in_features=512, out_features=5564, bias=True)
        (decoders): ModuleList(
          (0-2): 3 x DecoderLayer(
            (self_attn): MultiHeadedAttention(
              (linear_q): Linear(in_features=512, out_features=512, bias=True)
              (linear_k): Linear(in_features=512, out_features=512, bias=True)
              (linear_v): Linear(in_features=512, out_features=512, bias=True)
              (linear_out): Linear(in_features=512, out_features=512, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (src_attn): MultiHeadedCrossAttention(
              (linear_q): Linear(in_features=512, out_features=512, bias=True)
              (linear_k): Linear(in_features=512, out_features=512, bias=True)
              (linear_v): Linear(in_features=512, out_features=512, bias=True)
              (linear_out): Linear(in_features=512, out_features=512, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (feed_forward): PositionwiseFeedForward(
              (w_1): Linear(in_features=512, out_features=2048, bias=True)
              (activation): ReLU()
              (dropout): Dropout(p=0.1, inplace=False)
              (w_2): Linear(in_features=2048, out_features=512, bias=True)
            )
            (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
            (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
            (norm3): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (right_decoder): TransformerDecoder(
        (embed): Sequential(
          (0): Embedding(5564, 512)
          (1): PositionalEncoding(
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (after_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (output_layer): Linear(in_features=512, out_features=5564, bias=True)
        (decoders): ModuleList(
          (0-2): 3 x DecoderLayer(
            (self_attn): MultiHeadedAttention(
              (linear_q): Linear(in_features=512, out_features=512, bias=True)
              (linear_k): Linear(in_features=512, out_features=512, bias=True)
              (linear_v): Linear(in_features=512, out_features=512, bias=True)
              (linear_out): Linear(in_features=512, out_features=512, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (src_attn): MultiHeadedCrossAttention(
              (linear_q): Linear(in_features=512, out_features=512, bias=True)
              (linear_k): Linear(in_features=512, out_features=512, bias=True)
              (linear_v): Linear(in_features=512, out_features=512, bias=True)
              (linear_out): Linear(in_features=512, out_features=512, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (feed_forward): PositionwiseFeedForward(
              (w_1): Linear(in_features=512, out_features=2048, bias=True)
              (activation): ReLU()
              (dropout): Dropout(p=0.1, inplace=False)
              (w_2): Linear(in_features=2048, out_features=512, bias=True)
            )
            (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
            (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
            (norm3): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (ctc): CTC(
      (ctc_lo): Linear(in_features=512, out_features=5564, bias=True)
      (ctc_loss): CTCLoss()
    )
    (criterion_att): LabelSmoothingLoss(
      (criterion): KLDivLoss()
    )
  )
) ----
2024-07-12 18:36:43,106 INFO Epoch 0 Step 0 TRAIN info lr 2.0000e-08 rank 0
2024-07-12 18:36:43,135 INFO using accumulate grad, new batch size is 16 times larger than before
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/SpeechRecognitioin/wenet/examples/aishell/s0/wenet/bin/train.py", line 187, in <module>
[rank0]:     main()
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
[rank0]:     return f(*args, **kwargs)
[rank0]:   File "/home/SpeechRecognitioin/wenet/examples/aishell/s0/wenet/bin/train.py", line 155, in main
[rank0]:     executor.train(model, optimizer, scheduler, train_data_loader,
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/utils/executor.py", line 84, in train
[rank0]:     info_dict = batch_forward(model, batch_dict, scaler,
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/utils/train_utils.py", line 663, in batch_forward
[rank0]:     loss_dict = model(batch, device)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1593, in forward
[rank0]:     else self._run_ddp_forward(*inputs, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1411, in _run_ddp_forward
[rank0]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/transformer/asr_model.py", line 113, in forward
[rank0]:     loss_att, acc_att = self._calc_att_loss(
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/transformer/asr_model.py", line 191, in _calc_att_loss
[rank0]:     decoder_out, r_decoder_out, _ = self.decoder(encoder_out, encoder_mask,
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/transformer/decoder.py", line 455, in forward
[rank0]:     l_x, _, olens = self.left_decoder(memory, memory_mask, ys_in_pad,
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/transformer/decoder.py", line 195, in forward
[rank0]:     x = self.forward_layers(x, tgt_mask, memory, memory_mask)
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/transformer/decoder.py", line 207, in forward_layers
[rank0]:     x, tgt_mask, memory, memory_mask = layer(x, tgt_mask, memory,
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/transformer/decoder_layer.py", line 135, in forward
[rank0]:     x, new_cross_cache = self.src_attn(x,
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/transformer/attention.py", line 461, in forward
[rank0]:     q, k, v = self.forward_qkv(query, key, value)
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/transformer/attention.py", line 125, in forward_qkv
[rank0]:     v = self._forward_linearx('value', value)
[rank0]:   File "/home/SpeechRecognitioin/wenet/wenet/transformer/attention.py", line 95, in _forward_linearx
[rank0]:     x = self.linear_v(x)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/fspeech/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 116, in forward
[rank0]:     return F.linear(input, self.weight, self.bias)
[rank0]: RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasLtMatmul with transpose_mat1 1 transpose_mat2 0 m 512 n 5915 k 512 mat1_ld 512 mat2_ld 512 result_ld 51                                                2 abcType 0 computeType 68 scaleType 0
2024-07-12 18:37:29,226 DEBUG Attempting to acquire lock 140024755891712 on /root/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
2024-07-12 18:37:29,227 DEBUG Lock 140024755891712 acquired on /root/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
2024-07-12 18:37:29,227 DEBUG Attempting to release lock 140024755891712 on /root/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
2024-07-12 18:37:29,228 DEBUG Lock 140024755891712 released on /root/.triton/autotune/Fp16Matmul_2d_kernel.pickle.lock
2024-07-12 18:37:29,228 DEBUG Attempting to acquire lock 140024880855936 on /root/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
2024-07-12 18:37:29,229 DEBUG Lock 140024880855936 acquired on /root/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
2024-07-12 18:37:29,229 DEBUG Attempting to release lock 140024880855936 on /root/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
2024-07-12 18:37:29,229 DEBUG Lock 140024880855936 released on /root/.triton/autotune/Fp16Matmul_4d_kernel.pickle.lock
[rank0]:[W CUDAGuardImpl.h:118] Warning: CUDA warning: device-side assert triggered (function destroyEvent)
Fatal Python error: Aborted

Current thread 0x00007f5a1557d740 (most recent call first):
  <no Python frame>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator,                                                 numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft                                                , torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, yaml._yaml, _cffi_backend, charset_normalizer.md, simplejson._speedups, requests.packages.charset_n                                                ormalizer.md, requests.packages.chardet.md, regex._regex, scipy._lib._ccallback_c, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._n                                                rt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, psutil._psutil_linux, psutil._psutil_posix, cython.cimports.libc.math, sentencepiece._sentencepiece, google._upb._mes                                                sage (total: 40)
E0712 18:37:41.033944 139737440794432 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -6) local_rank: 0 (pid: 137033) of binary: /root/anaconda3/envs/fspeech/bin/py                                                thon3.1
E0712 18:37:41.048840 139737440794432 torch/distributed/elastic/multiprocessing/errors/error_handler.py:136] no error file defined for parent, to copy child error file (/tmp/torchelastic_k                                                zpoom8_/2023_kcwt4lsd/attempt_0/0/error.json)
