### ISSUE TITLE
'shard' and 'raw' have same training speed.

### ISSUE THREAD

**Issue by peggyxpxu** [wenet-e2e/wenet#781]
When preprocessing data, I don't generate tar, but directly save WAV and TXT in the folder, and then used 'raw' for training,  training speed is almost the same with 'shard'.

**Comment by robin1001** [comment]
shard is faster than raw on very large data.

**Comment by peggyxpxu** [comment]
> shard is faster than raw on very large data.

How many hours above is very large data?

**Comment by duj12** [comment]
> shard is faster than raw on very large data.

@robin1001 do you have an example? like the training speed of some specific hours' data when using shard and raw,  respectively.

**Comment by duj12** [comment]
> > shard is faster than raw on very large data.
> 
> @robin1001 do you have an example? like the training speed of some specific hours' data when using shard and raw, respectively.

I use more than 30k hours data, and 8A100 GPU with 16 accum_grad, 50 batch_size, and 8 num_workers. When use raw data, i get ahout 100sec/100batches. 
the log is as following:
![image](https://user-images.githubusercontent.com/37294470/211794461-db711047-6c01-4cf3-a9fa-c87b3b4ce02c.png)

I wonder how fast when I use "shard" mode, I will do some experiment later.

**Comment by duj12** [comment]
> > > shard is faster than raw on very large data.
> > 
> > 
> > @robin1001 do you have an example? like the training speed of some specific hours' data when using shard and raw, respectively.
> 
> I use more than 30k hours data, and 8A100 GPU with 16 accum_grad, 50 batch_size, and 8 num_workers. When use raw data, i get ahout 100sec/100batches. the log is as following: ![image](https://user-images.githubusercontent.com/37294470/211794461-db711047-6c01-4cf3-a9fa-c87b3b4ce02c.png)
> 
> I wonder how fast when I use "shard" mode, I will do some experiment later.

I use shard mode, with 8A100，16 accum_grad, 32 batch_size(because max_length of audio increase from 12s to 20s), and 8 num_workers, and I get the following log:

![image](https://user-images.githubusercontent.com/37294470/212271478-4954bd12-7dc6-429f-9073-810ac0da6537.png)

considering the decrease of batch_size(the speed of per 100batch will be faster), the total net speed of shard is truely faster than raw. 

Additionally, the TAR operation of the total 30k hours' data cost about 26 hours, which is worthy. 
Another advantage of using SHARD mode I think is its training stability. When I use raw mode, training will be slower when runing last some time, and the training even could be stuck, because of IO. For now, SHARD mode is satisfactory.
